
###
#
# Browse Books
#
GET http://localhost:4004/odata/v4/catalog/Books?
  # &$select=title,stock
  # &$expand=currency
  # &sap-language=de

###
#
# Get Author wit ID 101
#
GET http://localhost:4004/odata/v4/catalog/Authors(101)

###
#
# Update Author with ID 101
#
POST http://localhost:4004/odata/v4/catalog/Authors
Content-Type: application/json

{"ID": 101, "name": "Some Author"}


###
#
# Order a Book
#
POST http://localhost:4004/odata/v4/catalog/Orders
Content-Type: application/json;IEEE754Compatible=true

{"book_ID": 201, "amount": 5}

###
GET http://localhost:4004/odata/v4/catalog/Events

###
POST http://localhost:4004/odata/v4/catalog/Users
Content-Type: application/json

{"name": "Some User"}

###
GET http://localhost:4004/odata/v4/catalog/Users
###
DELETE http://localhost:4004/odata/v4/catalog/Users(xx)

###
GET http://localhost:4004/odata/v4/catalog/Feedback

###
POST http://localhost:4004/odata/v4/catalog/Feedback

###
POST http://localhost:4004/odata/v4/catalog/PasswordReset
Content-Type: application/json

{"userEmail": "test@gmail.com "}